Little funny mapper
BobIsOnFire/caesar-rs pull request #1
Opened 2021-09-13 21:51 UTC by EgorkaZ

2021-09-13 22:03 UTC, EgorkaZ commented on src/alphabet_map.rs
> +use rustc_hash::FxHashMap;
Exactly casual `HashMap`, but has a faster hash function. Should be good for integral type like `char`

2021-09-13 22:18 UTC, BobIsOnFire requested changes
<3

2021-09-13 22:18 UTC, BobIsOnFire commented on src/lib.rs
> +    panic!("Character {} is not found in alphabet: [{}]", ch, ALPHABET)
Could you please return char codes into panic message? I could see a confusion if it says that char 'А' (cyrillic) is not found in alphabet [ABC] (latin)

2021-09-13 22:18 UTC, BobIsOnFire commented on src/lib.rs
> -    pub fn encrypt(&self, input: String) -> String {
We should have interfaces for both `String` and `Iterator`. I love the possibility to read from char stream or something like that, but most of the cases are actually about transforming strings and they cause additional function calls outside of the interface.
How about `encrypt` and `encrypt_stream`?

2021-09-13 22:18 UTC, BobIsOnFire commented on src/lib.rs
> -        check_alphabet(&input);
Is it ever checked that input is a part of alphabet? Apart from `by_idx` call which does not fail gracefully

2021-09-15 05:33 UTC, BobIsOnFire approved these changes

2021-09-15 05:51 UTC, merged